name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          password: ${{secrets.SSH_PASSWORD}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            if [ -d "app" ]; then
              echo "Dir app already exists"
            else
              mkdir app 
            fi
            cd app
            if [ -d "cloud-sigma" ]; then
              echo "Repository already cloned, pulling latest changes"
              cd cloud-sigma
              git pull
            else
              echo "Cloning repository for the first time"
              git clone https://${{ secrets.TOKEN }}@github.com/branchev/cloud-sigma.git
            fi
